// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function fizzbuzz(i) {
  var exit = 0;
  var match_000 = i % 3;
  var match_001 = /* :: */[
    i % 5,
    /* [] */0
  ];
  if (match_000 !== 0) {
    var match = match_001;
    if (match) {
      if (match[0] !== 0) {
        if (match[1]) {
          exit = 1;
        } else {
          return String(i);
        }
      } else if (match[1]) {
        exit = 1;
      } else {
        return "Buzz";
      }
    } else {
      exit = 1;
    }
  } else {
    var match$1 = match_001;
    if (match$1) {
      if (match$1[0] !== 0) {
        if (match$1[1]) {
          exit = 1;
        } else {
          return "Fizz";
        }
      } else if (match$1[1]) {
        exit = 1;
      } else {
        return "FizzBuzz";
      }
    } else {
      exit = 1;
    }
  }
  if (exit === 1) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "fizzbuz.re",
            2,
            2
          ]
        ];
  }
  
}

for(var i = 1; i <= 100; ++i){
  console.log(fizzbuzz(i));
}

exports.fizzbuzz = fizzbuzz;
/*  Not a pure module */
